CLIENT_ID = "iot_device_2"
ENDPOINT = "a1ws5sttxtfldm-ats.iot.ap-northeast-1.amazonaws.com"
ROOT_CA     = "root-CA.crt"
PRIVATE_KEY = "iot_device_2.private.key"
CERT        = "iot_device_2.cert.pem"
DEVICE_ID = "iot123456"
AWS_THING = "iot_device_2"
